# Generated by Django 4.1.3 on 2022-11-21 07:23

import ckeditor.fields
from django.db import migrations, models
import other.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='blog _images', validators=[other.utils.rasm_olchami])),
                ('des', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Name')),
                ('facebook', models.URLField(blank=True, max_length=40, null=True, verbose_name='Facebook')),
                ('telegram', models.URLField(blank=True, max_length=40, null=True, verbose_name='Telegram')),
                ('youtube', models.URLField(blank=True, max_length=40, null=True, verbose_name='Youtube')),
                ('instagram', models.URLField(blank=True, max_length=40, null=True, verbose_name='Instagram')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', validators=[other.utils.logo_size], verbose_name='Logo')),
                ('location', models.URLField(blank=True, max_length=300, null=True, verbose_name='Location')),
                ('locationiframe', models.URLField(blank=True, max_length=400, null=True, verbose_name='Location for Contact')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.CharField(blank=True, max_length=20, null=True, verbose_name='Email')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('about_us', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About Us')),
                ('about_us_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='About Us Image')),
            ],
        ),
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='blog _images', validators=[other.utils.image_size])),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='team_image')),
                ('facebook', models.CharField(blank=True, max_length=40, null=True, verbose_name='Facebook')),
                ('telegram', models.CharField(blank=True, max_length=40, null=True, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=40, null=True, verbose_name='Instagram')),
            ],
        ),
    ]
